adding router
jivoryy/binar-ch7-groupquiz pull request #3
Opened 2022-04-12 21:32 UTC by yeremib

2022-04-13 02:12 UTC, jivoryy requested changes
mas Yeremi, Controllernya dimana ya? ini cuma ada file routes tapi juga nggak ada isinya.. Kalau kesulitan bisa woro-woro di grup atau by pm tele juga nggak apa mas Yeremi..

2022-04-13 08:42 UTC, jivoryy requested changes
functionnya ya mas, dipindah ke controller biar MVC..

2022-04-13 16:17 UTC, yeremib commented
sudah dipindah ke controller ya mas, tolong direview. Thank you mas.

2022-04-14 01:54 UTC, jivoryy approved these changes
Makasih banyak mas Yeremi!

2022-04-14 01:54 UTC, merged